name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install system deps (audio tools minimal)
        run: sudo apt-get update && sudo apt-get install -y espeak-ng

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit

      - name: Lint (pre-commit)
        run: |
          pre-commit run --all-files --show-diff-on-failure

      - name: Run tests
        env:
          CI: true
        run: |
          pytest -q
